import pygame as pg

pg.mixer.init()  

#Цвета
CREAM = (253, 244, 227)
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)
LIGHT_RED = (255,114,118)

#Стандартные значения переменных, связанных с геймплеем
DEFAULT_SHOOT_DELAY = 200
DEFAULT_PLAYER_MOV_SPEED = 10
DEFAULT_DAMAGED_TIME = 2000
DEFAULT_MOB_MOV_SPEED = 8
DEFAULT_PLAYER_BULLET_MOV_SPEED = -10
DEFAULT_MOB_BULLET_MOV_SPEED = 5
DEFAULT_MOB_SHOOT_CHANCE = 1
DEFAULT_MOB_HEALTH = 5
DEFAULT_MAX_MOB_NUM = 10
DEFAULT_PLAYER_HEALTH = 10
DEFAULT_KILL_POINTS = 100
BONUS_DURATION = 6000
BONUS_LIFETIME = 5000
BONUS_ANIMATION = 0.1
DEFAULT_BONUS_HEAL = 1
DEFAULT_BONUS_SPEED = 1
DEFAULT_BONUS_DROP_CHANCE = 25
FPS = 150 # частота кадров в секунду

#Стандартные значения переменных, связанных с экраном
WIDTH = 800#360  # ширина игрового окна
HEIGHT = 600#480 # высота игрового окна
DEFAULT_FONT_SIZE = 25
DEFAULT_BUTTON_WIDTH = 150
DEFAULT_BUTTON_HEIGHT = 75
HEALTH_BAR_COEF = 1/23
TEXTBOX_WIDTH = 200
TEXTBOX_HEIGHT = 50
TEXTBOX_X_COEF = 1/2
TEXTBOX_Y_COEF = 2/5
DROPDOWN_WIDTH = 200
DROPDOWN_HEIGHT = 40
DROPDOWN_X_COEF = 1/5
DROPDOWN_Y_COEF = 1/5
SLIDER_WIDTH = 200
SLIDER_HEIGHT = 30
SLIDER_X_COEF = 1/5
SLIDER_Y_COEF = 1/2
SETTINGS_BUTTON_WIDTH = 100
SETTINGS_BUTTON_HEIGHT = 50
SCREEN_PART_FOR_BUTTON = 7
SCREEN_PART_FOR_SETTINGS_BUTTON = 8
MOB_SIZE_COEF_WIDTH = 15
MOB_SIZE_COEF_HEIGHT = 10
EXPLOSION_ANIMATION_TIME = 0.05
BONUS_SIZE = 25

#коэффициент для траекторий движения мобов
DEFAULT_COEF_ARC_TRAJ = 5

#Стандартные значения кнопок управления персонажами
DEFAULT_PLAYER_TWO_UP_BUTTON = pg.K_UP
DEFAULT_PLAYER_TWO_RIGHT_BUTTON = pg.K_RIGHT
DEFAULT_PLAYER_TWO_LEFT_BUTTON = pg.K_LEFT
DEFAULT_PLAYER_TWO_DOWN_BUTTON = pg.K_DOWN
DEFAULT_PLAYER_TWO_SHOOT_BUTTON = pg.K_RCTRL
#второй игрок
DEFAULT_PLAYER_ONE_UP_BUTTON = pg.K_w
DEFAULT_PLAYER_ONE_RIGHT_BUTTON = pg.K_d
DEFAULT_PLAYER_ONE_LEFT_BUTTON = pg.K_a
DEFAULT_PLAYER_ONE_DOWN_BUTTON = pg.K_s
DEFAULT_PLAYER_ONE_SHOOT_BUTTON = pg.K_SPACE
